#!/usr/bin/env bash
# Drift's web runtime needs two files in web/ whose versions must match the
# resolved packages: sqlite3.wasm (package:sqlite3) and drift_worker.js
# (package:drift).
#
#   tool/web_assets.sh fetch   download the versions in pubspec.lock and record
#                              their checksums in tool/web_assets.lock
#   tool/web_assets.sh check   fail if pubspec.lock, tool/web_assets.lock and
#                              the files in web/ disagree (run in CI)
set -euo pipefail
cd "$(dirname "$0")/.."

LOCK_FILE=tool/web_assets.lock

lock_version() {
  awk -v pkg="$1" '
    $0 == "  " pkg ":" { found = 1; next }
    found && /^    version:/ { gsub(/"/, "", $2); print $2; exit }
  ' pubspec.lock
}

sha256() {
  if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

recorded() { awk -v key="$1" '$1 == key { print $2 }' "$LOCK_FILE"; }

sqlite3_version=$(lock_version sqlite3)
drift_version=$(lock_version drift)

case "${1:-}" in
  fetch)
    curl -fsSL -o web/sqlite3.wasm \
      "https://github.com/simolus3/sqlite3.dart/releases/download/sqlite3-${sqlite3_version}/sqlite3.wasm"
    curl -fsSL -o web/drift_worker.js \
      "https://github.com/simolus3/drift/releases/download/drift-${drift_version}/drift_worker.js"
    {
      echo "# Generated by tool/web_assets.sh fetch. Do not edit."
      echo "sqlite3_version ${sqlite3_version}"
      echo "sqlite3_wasm_sha256 $(sha256 web/sqlite3.wasm)"
      echo "drift_version ${drift_version}"
      echo "drift_worker_sha256 $(sha256 web/drift_worker.js)"
    } > "$LOCK_FILE"
    echo "Fetched sqlite3.wasm ${sqlite3_version} and drift_worker.js ${drift_version}."
    ;;
  check)
    status=0
    fail() { echo "web assets: $1" >&2; status=1; }
    [[ "$(recorded sqlite3_version)" == "$sqlite3_version" ]] ||
      fail "sqlite3.wasm is for sqlite3 $(recorded sqlite3_version), pubspec.lock has ${sqlite3_version}. Run tool/web_assets.sh fetch."
    [[ "$(recorded drift_version)" == "$drift_version" ]] ||
      fail "drift_worker.js is for drift $(recorded drift_version), pubspec.lock has ${drift_version}. Run tool/web_assets.sh fetch."
    [[ "$(sha256 web/sqlite3.wasm)" == "$(recorded sqlite3_wasm_sha256)" ]] ||
      fail "web/sqlite3.wasm does not match its recorded checksum."
    [[ "$(sha256 web/drift_worker.js)" == "$(recorded drift_worker_sha256)" ]] ||
      fail "web/drift_worker.js does not match its recorded checksum."
    [[ $status == 0 ]] && echo "Web assets match pubspec.lock (sqlite3 ${sqlite3_version}, drift ${drift_version})."
    exit $status
    ;;
  *)
    echo "usage: $0 fetch|check" >&2
    exit 2
    ;;
esac
